[package]
name = "g-collector"
version = "0.1.0"
edition = "2021"

[dependencies]
thirtyfour = "0.31.0"
tokio = { version = "1.33.0" }
clap = { version = "4.4.7", features = ["derive"] }

[dev-dependencies]
